# Generated by Django 5.2.11 on 2026-03-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_expiration', models.PositiveIntegerField(default=7)),
            ],
            options={
                'verbose_name': 'Configuração de Alertas',
            },
        ),
    ]
