# Generated by Django 5.2.11 on 2026-03-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
