# Generated by Django 5.2.11 on 2026-03-31 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_batch_product_alter_batch_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
