# Generated by Django 5.2.11 on 2026-03-26 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0002_initial'),
        ('inventory', '0003_alter_batch_product_alter_batch_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.batch'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='quantity_used',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
